"""
scripts/akinator/manual_traits.py — label the head by hand (or by Claude).

    python scripts/akinator/manual_traits.py dump  --start 0 --count 60
    python scripts/akinator/manual_traits.py ingest labels.json

WHY THIS EXISTS. Trait extraction is blocked on free-tier quota: Gemini
allows 15 requests a minute per key and Groq's token ceiling stops real
prompts after four. The corpus needs ~1.13M tokens even after batching, so
the model route is a multi-day job unless more keys are added.

But the corpus does not need labelling evenly. **The popularity prior means
the head is where players' guesses land**, and the head is small: the top
600 books are ~58K tokens of description, which is a session's work rather
than a week's. Labelling those well beats labelling all 3,570 badly.

So this reads out compact batches for a careful reader — a person, or the
assistant in a session — and reads labels back in the same shape the model
path writes. **One output file, `akinator_traits.json`**, so the pipeline
downstream cannot tell which route produced a label and does not need to.

The two routes are complementary, not rivals: do the head by hand now, let
the model fill the tail whenever quota allows. `ingest` never overwrites an
existing label unless asked, so whichever runs second cannot clobber the
first.

GROUNDING IS UNCHANGED and applies to a human reader exactly as it does to
a model. A label is a claim about the book; a wrong one eliminates the
correct answer with confidence. Label only what the description supports,
leave the rest out, and an empty list is a valid answer.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from traits import OUT_PATH, TRAITS  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DESC_PATH = os.path.join(REPO_ROOT, "data", "akinator_descriptions.json")

# Enough to judge the traits; the rest is plot detail that costs tokens
# without changing the answer.
SNIPPET = 420


def _ordered_with_text() -> list[tuple[dict, str]]:
    from simulate import load_docs
    with open(DESC_PATH, encoding="utf-8") as fh:
        desc = json.load(fh)
    return [(d, desc[d["key"]]) for d in load_docs(5000) if d.get("key") in desc]


def dump(start: int, count: int) -> None:
    rows = _ordered_with_text()[start:start + count]
    print(f"# books {start}..{start + len(rows) - 1} of "
          f"{len(_ordered_with_text())}")
    print(f"# labels: {' '.join(TRAITS)}")
    for i, (doc, text) in enumerate(rows, start):
        title = (doc.get("title") or "")[:70]
        author = ((doc.get("author_name") or [""])[0])[:34]
        body = " ".join(text[:SNIPPET].split())
        print(f"\n[{i}] {title} — {author}\n{body}")


def ingest(path: str, overwrite: bool = False) -> None:
    """Read {index: [labels]} and store it against the right work keys.

    Indices, not titles: a title typed back by hand is a chance to attach
    labels to the wrong book, and the index is generated by `dump` from the
    same ordering this reads.
    """
    with open(path, encoding="utf-8") as fh:
        given = json.load(fh)

    rows = _ordered_with_text()
    out: dict[str, list[str]] = {}
    if os.path.exists(OUT_PATH):
        with open(OUT_PATH, encoding="utf-8") as fh:
            saved = json.load(fh)
        out = saved.get("traits", saved)

    added = skipped = bad = 0
    for raw_index, labels in given.items():
        try:
            i = int(raw_index)
        except (TypeError, ValueError):
            bad += 1
            continue
        if not (0 <= i < len(rows)) or not isinstance(labels, list):
            bad += 1
            continue
        key = rows[i][0]["key"]
        if key in out and not overwrite:
            skipped += 1
            continue
        clean = sorted({l for l in labels if isinstance(l, str) and l in TRAITS})
        dropped = [l for l in labels if l not in TRAITS]
        if dropped:
            print(f"  . [{i}] dropped unknown label(s): {dropped}",
                  file=sys.stderr)
        out[key] = clean
        added += 1

    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        json.dump({"traits": out}, fh, ensure_ascii=False)

    print(f"ingested {added}, skipped {skipped} already present, "
          f"{bad} malformed")
    print(f"total labelled: {len(out)} -> {OUT_PATH}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    d = sub.add_parser("dump")
    d.add_argument("--start", type=int, default=0)
    d.add_argument("--count", type=int, default=60)
    g = sub.add_parser("ingest")
    g.add_argument("path")
    g.add_argument("--overwrite", action="store_true")
    args = ap.parse_args()

    if args.cmd == "dump":
        dump(args.start, args.count)
    else:
        ingest(args.path, args.overwrite)


if __name__ == "__main__":
    main()
